### ISSUE TITLE
Conflicting package names with maketechnology/chromium.swt

### ISSUE THREAD

**Issue by nedtwigg** [dschaefer/swt-cef#1]
As you [mentioned on twitter](https://twitter.com/dougschaefer/status/1090276740277174273), this is currently an experiment, and you need GTK3 support which `chromium.swt` [doesn't have yet](https://github.com/maketechnology/chromium.swt/issues/17).

It might be nice to compare these projects head-to-head in the future so that they can learn from each other, but it'll be a little tricky because both are using the same package and class names.

- https://github.com/dschaefer/swt-cef/tree/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium
- https://github.com/maketechnology/chromium.swt/tree/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium

Just a heads up that it might be easier for these projects to coexist and cooperate in the future if the package names are at least a little different.

**Comment by dschaefer** [comment]
Sounds reasonable. Not sure I'm comfortable using the swt namespace here yet anyway since, given the size of the cef library, it should probably be in an optional package.

I also need to write up build instructions since we're assuming libcef and friends are in the cef directory. And I'm currently using a native binary for the secondary processes and need to discuss the build for that. Mind you I probably could do that process in Java too. JNA is pretty nice to work with and should make that feasible.

**Comment by dschaefer** [comment]
I've renamed them to org.eclipse.swt.cef since the focus here is on CEF and providing programmatic access to it, not necessarily about providing a Chromium SWT Browser widget, though that should be doable under this strategy.
